database:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "123456"
  dbname: "ledger_db"
jwt:
  secret: "my_secret_key_12345"
ai:
  api_key: "${AI_API_KEY}"
  base_url: "${AI_BASE_URL}"
  model: "${AI_MODEL}"